const arr1 = [12, 64, 27, 21, 83, 62, 49];
const arr2 = arr1;
arr1.push(55);
// console.log(arr1);
// console.log(arr2);
console.log(...arr1);
const highest = Math.max(...arr1);
console.log(highest);
const lowest = Math.min(...arr1);
console.log(lowest);
const arr3 = [...arr1, 90];
arr3.push(69);
console.log(arr3);
console.log(arr1);
arr3.shift();
console.log(arr3);
console.log(arr1);
